const mongoose = require("mongoose");

const shippSchema = new mongoose.Schema({
  wilayas: {
    type: String,
    required: true,
    enum: [
      "Adrar",
      "Chlef",
      "Laghouat",
      "Oum El Bouaghi",
      "Batna",
      "Béjaïa",
      "Biskra",
      "Béchar",
      "Blida",
      "Bouïra",
      "Tamanrasset",
      "Tébessa",
      "Tlemcen",
      "Tiaret",
      "Tizi Ouzou",
      "Algiers",
      "Djelfa",
      "Jijel",
      "Sétif",
      "Saïda",
      "Skikda",
      "Sidi Bel Abbès",
      "Annaba",
      "Guelma",
      "Constantine",
      "Médéa",
      "Mostaganem",
      "M'Sila",
      "Mascara",
      "Ouargla",
      "Oran",
      "El Bayadh",
      "Illizi",
      "Bordj Bou Arréridj",
      "Boumerdès",
      "El Tarf",
      "Tindouf",
      "Tissemsilt",
      "El Oued",
      "Khenchela",
      "Souk Ahras",
      "Tipaza",
      "Mila",
      "Aïn Defla",
      "Naâma",
      "Aïn Témouchent",
      "Ghardaïa",
      "Relizane",
      "Timimoun",
      "Bordj Badji Mokhtar",
      "Ouled Djellal",
      "Béni Abbès",
      "Ain Salah",
      "Ain Guezzam",
      "Touggourt",
      "Djanet",
      "El M'Ghair",
      "El Menia",
    ],
  },
  priceToDesktop: {
    type: Number,
    required: true,
    min: 0,
  },
  priceToHomme: {
    type: Number,
    required: true,
    min: 0,
  },
});

const Shipping = mongoose.model("Shipping", shippSchema);

module.exports = Shipping;
